#ifndef LCD_FONT_CN_H
#define LCD_FONT_CN_H

#include <stdint.h>

typedef enum
{
    LCD_CN_XI,
    LCD_CN_TONG,
    LCD_CN_AN,
    LCD_CN_QUAN,
    LCD_CN_ZHUANG,
    LCD_CN_TAI,
    LCD_CN_GU,
    LCD_CN_ZHANG,
    LCD_CN_JI,
    LCD_CN_TING,
    LCD_CN_DIAN,
    LCD_CN_YA,
    LCD_CN_REN,
    LCD_CN_WU,
    LCD_CN_YAO,
    LCD_CN_KONG,
    LCD_CN_SHI,
    LCD_CN_JUE,
    LCD_CN_KAN,
    LCD_CN_MEN,
    LCD_CN_GOU,
    LCD_CN_WEN,
    LCD_CN_DU,
    LCD_CN_MU,
    LCD_CN_BIAO,
    LCD_CN_ZHAN,
    LCD_CN_KONG2,
    LCD_CN_JIA,
    LCD_CN_RE,
    LCD_CN_ZI,
    LCD_CN_YOU,
    LCD_CN_XIAO,
    LCD_CN_CAI,
    LCD_CN_PAN,
    LCD_CN_JIE,
    LCD_CN_DUAN,
    LCD_CN_XUE,
    LCD_CN_LIANG,
    LCD_CN_GONG,
    LCD_CN_LV,
    LCD_CN_HUAN,
    LCD_CN_CHONG,
    LCD_CN_TAN,
    LCD_CN_SU,
    LCD_CN_JIN,
    LCD_CN_BI,
    LCD_CN_DI,
    LCD_CN_PAN2,
    LCD_CN_YUN,
    LCD_CN_FA,
    LCD_CN_SHE,
    LCD_CN_ZAI,
    LCD_CN_XIAN,
    LCD_CN_LI,
    LCD_CN_ZONG,
    LCD_CN_LIAN,
    LCD_CN_LU,
    LCD_CN_DANG,
    LCD_CN_QIAN,
    LCD_CN_JI2,
    LCD_CN_DING,
    LCD_CN_CHU,
    LCD_CN_SHI2,
    LCD_CN_HUA,
    LCD_CN_SHI3,
    LCD_CN_FOU,
    LCD_CN_WU2,
    LCD_CN_KAI,
    LCD_CN_GUAN,
    LCD_CN_SHU,
    LCD_CN_JU,
    LCD_CN_SHI4,
    LCD_CN_JIAN,
    LCD_CN_YE,
    LCD_CN_SHANG,
    LCD_CN_XIA,
    LCD_CN_DONG,
    LCD_CN_JIE2,
    LCD_CN_HUI,
    LCD_CN_FU,
    LCD_CN_CUO,
    LCD_CN_WU3,
    LCD_CN_JIU,
    LCD_CN_XU,
    LCD_CN_COUNT,
} Lcd_CnChar_e;

extern const uint8_t lcd_cn_font16[LCD_CN_COUNT][32];

/* 常用标签的枚举序列，末尾 LCD_CN_COUNT 作为结束标记 */
#define LCD_LABEL_SYS { LCD_CN_XI, LCD_CN_TONG, LCD_CN_COUNT }
#define LCD_LABEL_SAFE { LCD_CN_AN, LCD_CN_QUAN, LCD_CN_COUNT }
#define LCD_LABEL_STATE { LCD_CN_ZHUANG, LCD_CN_TAI, LCD_CN_COUNT }
#define LCD_LABEL_FAULT { LCD_CN_GU, LCD_CN_ZHANG, LCD_CN_COUNT }
#define LCD_LABEL_ESTOP { LCD_CN_JI, LCD_CN_TING, LCD_CN_COUNT }
#define LCD_LABEL_VOLT { LCD_CN_DIAN, LCD_CN_YA, LCD_CN_COUNT }
#define LCD_LABEL_TASK { LCD_CN_REN, LCD_CN_WU, LCD_CN_COUNT }
#define LCD_LABEL_RC { LCD_CN_YAO, LCD_CN_KONG, LCD_CN_COUNT }
#define LCD_LABEL_VISION { LCD_CN_SHI, LCD_CN_JUE, LCD_CN_COUNT }
#define LCD_LABEL_WATCHDOG { LCD_CN_KAN, LCD_CN_MEN, LCD_CN_GOU, LCD_CN_COUNT }
#define LCD_LABEL_TEMP { LCD_CN_WEN, LCD_CN_DU, LCD_CN_COUNT }
#define LCD_LABEL_TARGET { LCD_CN_MU, LCD_CN_BIAO, LCD_CN_COUNT }
#define LCD_LABEL_DUTY { LCD_CN_ZHAN, LCD_CN_KONG2, LCD_CN_COUNT }
#define LCD_LABEL_HEAT { LCD_CN_JIA, LCD_CN_RE, LCD_CN_COUNT }
#define LCD_LABEL_ATTITUDE { LCD_CN_ZI, LCD_CN_TAI, LCD_CN_COUNT }
#define LCD_LABEL_VALID { LCD_CN_YOU, LCD_CN_XIAO, LCD_CN_COUNT }
#define LCD_LABEL_REFEREE { LCD_CN_CAI, LCD_CN_PAN, LCD_CN_COUNT }
#define LCD_LABEL_STAGE { LCD_CN_JIE, LCD_CN_DUAN, LCD_CN_COUNT }
#define LCD_LABEL_HP { LCD_CN_XUE, LCD_CN_LIANG, LCD_CN_COUNT }
#define LCD_LABEL_POWER { LCD_CN_GONG, LCD_CN_LV, LCD_CN_COUNT }
#define LCD_LABEL_BUFFER { LCD_CN_HUAN, LCD_CN_CHONG, LCD_CN_COUNT }
#define LCD_LABEL_HEATQ { LCD_CN_RE, LCD_CN_LIANG, LCD_CN_COUNT }
#define LCD_LABEL_AMMO { LCD_CN_TAN, LCD_CN_LIANG, LCD_CN_COUNT }
#define LCD_LABEL_BULLET_SPEED { LCD_CN_TAN, LCD_CN_SU, LCD_CN_COUNT }
#define LCD_LABEL_COIN { LCD_CN_JIN, LCD_CN_BI, LCD_CN_COUNT }
#define LCD_LABEL_CHASSIS { LCD_CN_DI, LCD_CN_PAN2, LCD_CN_COUNT }
#define LCD_LABEL_GIMBAL { LCD_CN_YUN, LCD_CN_TAI, LCD_CN_COUNT }
#define LCD_LABEL_SHOOT { LCD_CN_FA, LCD_CN_SHE, LCD_CN_COUNT }
#define LCD_LABEL_ONLINE { LCD_CN_ZAI, LCD_CN_XIAN, LCD_CN_COUNT }
#define LCD_LABEL_OFFLINE { LCD_CN_LI, LCD_CN_XIAN, LCD_CN_COUNT }
#define LCD_LABEL_BUS { LCD_CN_ZONG, LCD_CN_XIAN, LCD_CN_COUNT }
#define LCD_LABEL_LINK { LCD_CN_LIAN, LCD_CN_LU, LCD_CN_COUNT }
#define LCD_LABEL_CURRENT { LCD_CN_DANG, LCD_CN_QIAN, LCD_CN_COUNT }
#define LCD_LABEL_MOTOR { LCD_CN_DIAN, LCD_CN_JI2, LCD_CN_COUNT }
#define LCD_LABEL_INIT { LCD_CN_CHU, LCD_CN_SHI2, LCD_CN_HUA, LCD_CN_COUNT }
#define LCD_LABEL_READY { LCD_CN_JIU, LCD_CN_XU, LCD_CN_COUNT }
#define LCD_LABEL_CALIB { LCD_CN_BIAO, LCD_CN_DING, LCD_CN_COUNT }
#define LCD_LABEL_YES { LCD_CN_SHI3, LCD_CN_COUNT }
#define LCD_LABEL_NO { LCD_CN_FOU, LCD_CN_COUNT }
#define LCD_LABEL_NONE { LCD_CN_WU2, LCD_CN_COUNT }
#define LCD_LABEL_OPEN { LCD_CN_KAI, LCD_CN_COUNT }
#define LCD_LABEL_CLOSE { LCD_CN_GUAN, LCD_CN_COUNT }
#define LCD_LABEL_PAGE { LCD_CN_YE, LCD_CN_COUNT }
#define LCD_LABEL_PREV { LCD_CN_SHANG, LCD_CN_YE, LCD_CN_COUNT }
#define LCD_LABEL_NEXT { LCD_CN_XIA, LCD_CN_YE, LCD_CN_COUNT }
#define LCD_LABEL_FREEZE { LCD_CN_DONG, LCD_CN_JIE2, LCD_CN_COUNT }
#define LCD_LABEL_RESUME { LCD_CN_HUI, LCD_CN_FU, LCD_CN_COUNT }
#define LCD_LABEL_ERROR { LCD_CN_CUO, LCD_CN_WU3, LCD_CN_COUNT }

#endif // LCD_FONT_CN_H
